### ISSUE TITLE
The format of the data files of self-training

### ISSUE THREAD

**Issue by heng1999** [YiguanLiao/Animal_Action#1]
I dont know the format of the pkl file to fit the models and I cant find the 'Data.create_dataset_(1-3).py' file, so that I cant train my own models. Can you help me and provide me with the the format of data file?

**Comment by DeepLabc** [comment]
[here](https://github.com/DeepLabc/Something/tree/main/utils)

**Comment by heng1999** [comment]
> [这里](https://github.com/DeepLabc/Something/tree/main/utils)
Thanks a lot!
