### ISSUE TITLE
apply to animals

### ISSUE THREAD

**Issue by cccyd1** [YiguanLiao/Animal_Action#6]
STGCN and MMSkeleton are both designed for humans. How can they be modified to be applied to animals?

**Comment by DeepLabc** [comment]
I retrained STGCN with my own animal dataset

**Comment by cccyd1** [comment]
thank you very much for your answer. Then I still have some more questions，did you retrain stgcn instead of mmskeleton? Because I saw that training with stgcn requires openpose, and I don’t know how to modify openpose to be suitable for animals. I see that the program you provided also has a training function. Is the model obtained from training as effective as the stgcn model?”

**Comment by cccyd1** [comment]
> 我用我自己的动物数据集重新训练了STGCN

thank you so much for your answer. Then I still have some more questions， I saw that training with stgcn requires openpose, 
 but I don’t know how to modify openpose to be suitable for animals. I see that the program you provided also has a training function. Is the model obtained from training as effective as the stgcn model?”
